### ISSUE TITLE
Error when running 'osmi new TryOsmi'

### ISSUE THREAD

**Issue by ddikodroid** [OsmiCSX/osmi#5]
I tried to run `osmi new TryOsmi`
It went well at first, then this  messages appear.

> [!] Error installing OpenSSL-Universal
> [!] /usr/local/bin/git clone https://github.com/krzyzanowskim/OpenSSL.git /var/folders/_7/0sbd2f6n0h92h82rbjfz0rbr0000gp/T/d20210211-9869-h7yfne --template= --single-branch --depth 1 --branch 1.1.180
> 
> Cloning into '/var/folders/_7/0sbd2f6n0h92h82rbjfz0rbr0000gp/T/d20210211-9869-h7yfne'...
> error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
> error: 1066 bytes of body are still expected
> fatal: the remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> 
> Aborting run
> An unexpected error was encountered. Please report it as a bug:
> Error
>     at CocoaPodsPackageManager._installAsync (/usr/local/lib/node_modules/pod-install/build/index.js:2:76150)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async CocoaPodsPackageManager.installAsync (/usr/local/lib/node_modules/pod-install/build/index.js:2:75550)
>     at async runAsync (/usr/local/lib/node_modules/pod-install/build/index.js:2:9010)
>     at async /usr/local/lib/node_modules/pod-install/build/index.js:2:9096
> 
> 
> A new version of `pod-install` is available
> You can update by running: yarn global add pod-install

**Comment by ddikodroid** [comment]
Fix `yarn global add pod-install`
